services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    environment:
      - TZ=Asia/Karachi
      - LOG_LEVEL=info
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_JITTER=30s
      # Check for updates every day at 4:00 AM
      - DIUN_WATCH_SCHEDULE=0 0 4 * * *

      - DIUN_NOTIF_MAIL_HOST=mail.mailo.com
      - DIUN_NOTIF_MAIL_PORT=465
      - DIUN_NOTIF_MAIL_SSL=true
      - DIUN_NOTIF_MAIL_INSECURESKIPVERIFY=false
      - DIUN_NOTIF_MAIL_USERNAME=${MAIL_FROM}
      - DIUN_NOTIF_MAIL_PASSWORD=${MAIL_PASSWORD}
      - DIUN_NOTIF_MAIL_FROM=${MAIL_FROM}
      - DIUN_NOTIF_MAIL_TO=${MAIL_TO}
      - DIUN_NOTIF_MAIL_TEMPLATETITLE="{{ .Entry.Image }} released"
      - DIUN_NOTIF_MAIL_TEMPLATEBODY="Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released."
    volumes:
      - /etc/diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - node-net
    restart: no

networks:
  node-net:
    external: true
